### PR TITLE
Update buildspec.yml

### PR DESCRIPTION
**Pull request by yiangmeng**

### CODE REVIEW

**Comment by yiangmeng** [comment]
I faced "_SchemaError(io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta): invalid object doesn't have additional properties_" error when using the current 1.10.3 kubectl version...

**Comment by vissree** [comment]
Faced the same error, thanks for the pull request. A small suggestion is to use the same version for both aws-iam-authenticator and kubectl.
```
curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.10/2019-08-14/bin/linux/amd64/aws-iam-authenticator
curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.10/2019-08-14/bin/linux/amd64/kubectl
```

**Comment by mike-henders** [comment]
The EKS workshop now deploys a version 1.14 Kubernetes cluster. Suggest installing version 1.14.6 of the tools.

```
curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
```

**Comment by rnzsgh** [comment]
Thanks for your edits. Kubectl has been updated in another PR. Please let me know if you still see issues.

**Pull request closed without merging**
